name: hnsd

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install unbound
      run: sudo apt install -y unbound libunbound-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install unbound
      run: brew install unbound
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    


